/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Vehiculos;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static proyectofinalrpg.ProyectoFinalRPG.pathVehiculos;

/**
 *
 * @author braya
 */
public class CrearVehiculos12 extends javax.swing.JFrame {
  
 public static LinkedList capsulavehiculo = new LinkedList();
    public int identificar;
  
    /**
     * Creates new form Vehiculos12
     */
    public CrearVehiculos12() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
     public void createBin(){
        ObjectOutputStream binario = null;
        try {
            String nameFile = jTextField2N.getText();
            File file = new File(nameFile);
            Vehiculos vehiculos = (Vehiculos) capsulavehiculo.getLast();
           
            binario = new ObjectOutputStream(new FileOutputStream(pathVehiculos+vehiculos.getNombreV()+".avion"));
            binario.writeObject(vehiculos);
            
        } catch (Exception ex) {
            ex.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                binario.close();
            } catch (IOException ex) {
                Logger.getLogger(CrearVehiculos12.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
  
    
   

    
   
      
      
      
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField6PR = new javax.swing.JTextField();
        jTextField5D = new javax.swing.JTextField();
        jTextField4P = new javax.swing.JTextField();
        jTextField3A = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField2N = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1T = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setText("REGRESAR");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 60));

        jComboBox5.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox5.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30", "50", "70", "90", "110", "130" }));
        jComboBox5.setToolTipText("");
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        jComboBox2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "6", "10", "14", "18", "22" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, -1));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox4.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "60", "70", "80", "90", "100", "110" }));
        jComboBox4.setToolTipText("");
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, -1));

        jTextField6PR.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6PR.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextField6PR.setForeground(new java.awt.Color(102, 255, 255));
        jTextField6PR.setText("PRECIO");
        jTextField6PR.setToolTipText("");
        getContentPane().add(jTextField6PR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, -1));

        jTextField5D.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5D.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextField5D.setForeground(new java.awt.Color(102, 255, 255));
        jTextField5D.setText("DEFENSA");
        jTextField5D.setToolTipText("");
        getContentPane().add(jTextField5D, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 190, -1));

        jTextField4P.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4P.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextField4P.setForeground(new java.awt.Color(102, 255, 255));
        jTextField4P.setText("PUNTERIA");
        jTextField4P.setToolTipText("");
        getContentPane().add(jTextField4P, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, -1));

        jTextField3A.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3A.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextField3A.setForeground(new java.awt.Color(102, 255, 255));
        jTextField3A.setText("ATAQUE");
        jTextField3A.setToolTipText("");
        getContentPane().add(jTextField3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, -1));

        jComboBox3.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7", "10", "14", "18", "22", "26" }));
        jComboBox3.setToolTipText("");
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        jTextField2N.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2N.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextField2N.setForeground(new java.awt.Color(102, 255, 255));
        jTextField2N.setText("NOMBRE DEL VEHICULO");
        jTextField2N.setToolTipText("");
        jTextField2N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2NActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2N, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TANQUE", "AVION" }));
        jComboBox1.setToolTipText("");
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jTextField1T.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1T.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextField1T.setForeground(new java.awt.Color(102, 255, 255));
        jTextField1T.setText("TIPO DE VEHICULO");
        jTextField1T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1TActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1T, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 255));
        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vehiculos.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(810, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(810, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(810, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 741, 376));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombreV = jTextField2N.getText();
        String punteriaV = jTextField4P.getText();
        String ataqueV = jTextField3A.getText();
        String defensaV = jTextField5D.getText();
        String tipoV = jTextField1T.getText();
        String precioV= jTextField6PR.getText();
  
    
    
   
        //NOMBRE DE LA PERSONA ATRUBUTOS
      
        Vehiculos av  = new Vehiculos (nombreV,punteriaV,ataqueV,defensaV, tipoV, precioV);
        capsulavehiculo.add(av);
        //Limpia
        jTextField2N.setText("");
        jTextField4P.setText("");
        jTextField3A.setText("");
        jTextField5D.setText("");
        jTextField1T.setText("");
        jTextField6PR.setText("");
        
        Vehiculos ve = (Vehiculos)capsulavehiculo.getLast();
        createBin();
// TODO
        
   
                                           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2NActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
         this.jTextField3A.setText(" "+jComboBox3.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jTextField1TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1TActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        this.jTextField4P.setText(" "+jComboBox4.getSelectedItem().toString());
        
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
         this.jTextField5D.setText(" "+jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
        this.jTextField6PR.setText(" "+jComboBox5.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculos12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculos12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculos12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVehiculos12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearVehiculos12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1T;
    private javax.swing.JTextField jTextField2N;
    private javax.swing.JTextField jTextField3A;
    private javax.swing.JTextField jTextField4P;
    private javax.swing.JTextField jTextField5D;
    private javax.swing.JTextField jTextField6PR;
    // End of variables declaration//GEN-END:variables
}
