/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author braya
 */
public class Escenario9 extends javax.swing.JFrame {
    
    
   
    
    //Instanciar Matriz para el boton
  JButton[][] matriz;

    /**
     * Creates new form Escenario
     */
    public Escenario9() {
        initComponents();
        
    }
    //Recorre el tablero
     public void escenario5(int filas, int columnas){
        matriz =  new JButton[filas][columnas];
        int[][] juego = new int[filas][columnas];
        Random n = new Random();
         boolean blanco = true;
         
        //estos for recorren mis filas y columnas en mi matriz
        for (int i = 0; i<filas; i++){
            for (int j = 0; j<columnas; j++){
                //variable random para usarlo en mi switch
                int c = (int)((Math.random()*3)+1);
                System.out.println(c);
                //aleatorio colores
                switch(c){
                    //si es una sera amarillo
                    case 1: 
                        juego[i][j]= 1;
                        matriz[i][j] = new JButton ();
                         matriz[i][j].setBounds((50*j), 50*i, 50, 50);
                          matriz[i][j].setBackground(Color.yellow);
                          break; // rompe mi ciclo
                        //si es 2 será rojo
                    case 2:
                        juego[i][j]= 2;
                        matriz[i][j] = new JButton();
                         matriz[i][j].setBounds((50*j), 50*i, 50, 50);
                          matriz[i][j].setBackground(Color.red);
                          break;
                        //3 azul
                    case 3:
                        juego[i][j]= 3;
                        matriz[i][j] = new JButton ();
                         matriz[i][j].setBounds((50*j), 50*i, 50, 50);
                          matriz[i][j].setBackground(Color.blue); //set background para ponerlo del color que le estamos diciendo en el case
                    break;
                    default:
                    break;
                    
                }
                matriz[i][j].setVisible(true);

                matriz[i][j].setBounds((50*j), 50*i, 50, 50); //tamaño
                
                
                
                jPanelT.add(matriz[i][j]); //lo añado a mi JPANEL
                
                 jPanelT.updateUI();
       jPanelT.setLayout(new GridLayout(filas, columnas)); //Diseño
            jPanelT.repaint();//lo pintara otra vez
            
            
             }
           
            blanco = !blanco;
        }
        //random para colocar mi icono 
        int d = (int) (Math.random()*4);
        int d2 = (int) (Math.random()*4);
              ImageIcon tanque = new ImageIcon("src/Imagenes/tanque.png");
        Icon iconoTanque = new ImageIcon(tanque.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        matriz[d][d2].setIcon(iconoTanque);
        juego[d][d2] = 5;
        
        int a = (int) (Math.random()*4);
        int a2 = (int) (Math.random()*4);
            ImageIcon avion = new ImageIcon("src/Imagenes/60517.png");
        Icon iconoAvion = new ImageIcon(avion.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
         matriz[a][a2].setIcon(iconoAvion);
        juego[a][a2] = 4;
        
        int b = (int) (Math.random()*4);
        int b2 = (int) (Math.random()*4);
            ImageIcon avion1 = new ImageIcon("src/Imagenes/60517.png");
        Icon iconoAvion1 = new ImageIcon(avion1.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
         matriz[b][b2].setIcon(iconoAvion1);
        juego[b][b2] = 4;
        
         }
        
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelT = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelTLayout = new javax.swing.GroupLayout(jPanelT);
        jPanelT.setLayout(jPanelTLayout);
        jPanelTLayout.setHorizontalGroup(
            jPanelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelTLayout.setVerticalGroup(
            jPanelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 560, 380));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setText("4*4");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 255, 255));
        jButton4.setText("CANCELAR");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 60));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 255));
        jButton3.setText("9*8");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 255));
        jButton2.setText("6*4");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tablero nuevo = new Tablero(4, 4);
        this.dispose();
        nuevo.setVisible(true);
       // escenario5(4, 4); //llamó a mi método de mi código de mi matriz
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tablero nuevo = new Tablero(6, 4);
        this.dispose();
        nuevo.setVisible(true);
        //escenario5(6, 4);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
        Tablero nuevo = new Tablero(8, 9);
        this.dispose();
        nuevo.setVisible(true);
        //escenario5(8,9);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escenario9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escenario9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escenario9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escenario9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escenario9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelT;
    // End of variables declaration//GEN-END:variables
}
