/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.ClaseUsuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import static proyectofinalrpg.ProyectoFinalRPG.pathUSUARIO;

/**
 *
 * @author braya
 */
public class Jugador7 extends javax.swing.JFrame {
    public static LinkedList listado = new LinkedList();
    public int asignar;

    /**
     * Creates new form Jugador7
     */
    public Jugador7() {
        initComponents();
          // Centrar Ventana
        this.setLocationRelativeTo(null);
    
    }
    
    
    
    public void createBinario(){
        ObjectOutputStream binario = null;
        try {
            String nameFile = jTextField1Nick.getText();
            File file = new File(nameFile);
            ClaseUsuario persona = (ClaseUsuario) listado.getLast();
           
            binario = new ObjectOutputStream(new FileOutputStream(pathUSUARIO+persona.getNickname()+".persona"));
          binario.writeObject(persona);
            
        } catch (Exception ex) {
            ex.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                binario.close();
            } catch (IOException ex) {
                Logger.getLogger(Jugador7.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1V1 = new javax.swing.JComboBox();
        jComboBox2V2 = new javax.swing.JComboBox();
        jComboBox3V3 = new javax.swing.JComboBox();
        jTextFieldV1 = new javax.swing.JTextField();
        jTextFieldV2 = new javax.swing.JTextField();
        jTextFieldV3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1Nick = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1V1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1V1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox1V1.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox1V1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VEHICULO", "TANQUE", "AVION" }));
        jComboBox1V1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1V1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1V1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 30));

        jComboBox2V2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox2V2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox2V2.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox2V2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VEHICULO", "TANQUE", "AVION" }));
        jComboBox2V2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2V2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2V2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 30));

        jComboBox3V3.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox3V3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jComboBox3V3.setForeground(new java.awt.Color(102, 255, 255));
        jComboBox3V3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VEHICULO", "TANQUE", "AVION" }));
        jComboBox3V3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3V3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox3V3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        jTextFieldV1.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldV1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextFieldV1.setForeground(new java.awt.Color(102, 255, 255));
        jTextFieldV1.setText("NOMBRE VEHICULO");
        getContentPane().add(jTextFieldV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jTextFieldV2.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldV2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextFieldV2.setForeground(new java.awt.Color(102, 255, 255));
        jTextFieldV2.setText("NOMBRE VEHICULO");
        getContentPane().add(jTextFieldV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jTextFieldV3.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldV3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jTextFieldV3.setForeground(new java.awt.Color(102, 255, 255));
        jTextFieldV3.setText("NOMBRE VEHICULO");
        getContentPane().add(jTextFieldV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setDisplayedMnemonic('0');
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, 30));

        jLabel4.setDisplayedMnemonic('0');
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 30));

        jLabel5.setDisplayedMnemonic('0');
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 20, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("VEHICULOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 40));

        jTextField1Nick.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1Nick.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jTextField1Nick.setForeground(new java.awt.Color(102, 255, 255));
        jTextField1Nick.setText("NICKNAME");
        getContentPane().add(jTextField1Nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ciscoplay.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 120));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 255, 255));
        jButton3.setText("JUGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 255, 255));
        jButton4.setText("GUARDAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 50));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 255, 255));
        jButton5.setText("REGRESAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 274, -1, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel1.setDisplayedMnemonic('0');
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Regreso Ventana ModalidadJuego6
        
        ModalidadJuego6 modo = new ModalidadJuego6();
        modo.show();
        //Cerrar Ventana Jugador7
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1V1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1V1ItemStateChanged
        //Enviar mensaje a textfield
        this.jTextField1.setText(" "+jComboBox1V1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1V1ItemStateChanged

    private void jComboBox2V2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2V2ItemStateChanged
        // Enviar mensjae a textfield
         this.jTextField2.setText(" "+jComboBox2V2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2V2ItemStateChanged

    private void jComboBox3V3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3V3ItemStateChanged
        // Enviar mensaje a textfield
         this.jTextField3.setText(" "+jComboBox3V3.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox3V3ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
         String nickname = jTextField1Nick.getText();
     String Nvehiculo1 = jTextFieldV1.getText();
     String Nvehiculo2= jTextFieldV2.getText();
     String Nvehiculo3 = jTextFieldV3.getText();
     String Clase1 = jTextField1.getText();
     String Clase2 = jTextField2.getText();
     String Clase3 = jTextField2.getText();
     
        //NOMBRE DE LA PERSONA ATRUBUTOS
       ClaseUsuario persona = new ClaseUsuario(nickname,Nvehiculo1, Nvehiculo2,Nvehiculo3, Clase1,  Clase2,Clase3);
        listado.add(persona);
        
        //Limpia
        jTextField1Nick.setText("");
        jTextFieldV1.setText("");
        jTextFieldV2.setText("");
       jTextFieldV3.setText("");
     
        ClaseUsuario p = (ClaseUsuario)listado.getLast();
        createBinario();
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Abrir Ventana Escenario9
        
        Escenario9 tablero = new Escenario9();
        tablero.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1V1;
    private javax.swing.JComboBox jComboBox2V2;
    private javax.swing.JComboBox jComboBox3V3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField1Nick;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextFieldV1;
    public static javax.swing.JTextField jTextFieldV2;
    public static javax.swing.JTextField jTextFieldV3;
    // End of variables declaration//GEN-END:variables
}
