/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Dados;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author braya
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero(int filas, int columnas) {
        initComponents();
        escenario5(filas, columnas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelT = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblCuatro = new javax.swing.JLabel();
        lblCien = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanelTLayout = new javax.swing.GroupLayout(jPanelT);
        jPanelT.setLayout(jPanelTLayout);
        jPanelTLayout.setHorizontalGroup(
            jPanelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanelTLayout.setVerticalGroup(
            jPanelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 0, 470, 400));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dado-imagen-animada-0094.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 198, 146));

        lblCuatro.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        getContentPane().add(lblCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 125, 53));

        lblCien.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        getContentPane().add(lblCien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 125, 53));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dado-imagen-animada-0094.gif"))); // NOI18N
        jButton2.setText("100");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 198, 153));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 125, 53));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("ATAQUE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("COMODIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Dados cuatro = new Dados();
       cuatro.dadoDeCuatro();
       lblCuatro.setText(String.valueOf(cuatro.dadoDeCuatro()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dados cuatro = new Dados();
       cuatro.dadoDeCien();
        lblCuatro.setText(String.valueOf(cuatro.dadoDeCien()));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    public void escenario5(int filas, int columnas){
        matriz =  new JButton[filas][columnas];
        int[][] juego = new int[filas][columnas];
        Random n = new Random();
         boolean blanco = true;
         
        //estos for recorren mis filas y columnas en mi matriz
        for (int i = 0; i<filas; i++){
            for (int j = 0; j<columnas; j++){
                //variable random para usarlo en mi switch
                int c = (int)((Math.random()*3)+1);
                System.out.println(c);
                //aleatorio colores
                switch(c){
                    //si es una sera amarillo
                    case 1: 
                        juego[i][j]= 1;
                        matriz[i][j] = new JButton ();
                         matriz[i][j].setBounds((50*j), 50*i, 50, 50);
                          matriz[i][j].setBackground(Color.yellow);
                          break; // rompe mi ciclo
                        //si es 2 será rojo
                    case 2:
                        juego[i][j]= 2;
                        matriz[i][j] = new JButton();
                         matriz[i][j].setBounds((50*j), 50*i, 50, 50);
                          matriz[i][j].setBackground(Color.red);
                          break;
                        //3 azul
                    case 3:
                        juego[i][j]= 3;
                        matriz[i][j] = new JButton ();
                         matriz[i][j].setBounds((50*j), 50*i, 50, 50);
                          matriz[i][j].setBackground(Color.blue); //set background para ponerlo del color que le estamos diciendo en el case
                    break;
                    default:
                    break;
                    
                }
                matriz[i][j].setVisible(true);

                matriz[i][j].setBounds((50*j), 50*i, 50, 50); //tamaño
                
                
                
                jPanelT.add(matriz[i][j]); //lo añado a mi JPANEL
                
                 jPanelT.updateUI();
       jPanelT.setLayout(new GridLayout(filas, columnas)); //Diseño
            jPanelT.repaint();//lo pintara otra vez
            
            
             }
           
            blanco = !blanco;
        }
         int d = (int) (Math.random()*4);
        int d2 = (int) (Math.random()*4);
              ImageIcon tanque = new ImageIcon("src/Imagenes/tanque.png");
        Icon iconoTanque = new ImageIcon(tanque.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        matriz[d][d2].setIcon(iconoTanque);
        juego[d][d2] = 5;
        
        int a = (int) (Math.random()*4);
        int a2 = (int) (Math.random()*4);
            ImageIcon avion = new ImageIcon("src/Imagenes/60517.png");
        Icon iconoAvion = new ImageIcon(avion.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
         matriz[a][a2].setIcon(iconoAvion);
        juego[a][a2] = 4;
        
        int b = (int) (Math.random()*4);
        int b2 = (int) (Math.random()*4);
            ImageIcon avion1 = new ImageIcon("src/Imagenes/60517.png");
        Icon iconoAvion1 = new ImageIcon(avion1.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
         matriz[b][b2].setIcon(iconoAvion1);
        juego[b][b2] = 4;
        
        
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelT;
    private javax.swing.JLabel lblCien;
    private javax.swing.JLabel lblCuatro;
    // End of variables declaration//GEN-END:variables

  JButton[][] matriz;

  
    }
