/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Vehiculos;
import static Interfaces.CrearVehiculos12.capsulavehiculo;
import static Interfaces.Jugador7.jTextField1Nick;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyectofinalrpg.ProyectoFinalRPG.pathVehiculos;

/**
 *
 * @author braya
 */
public class Vehiculos13 extends javax.swing.JFrame {
   private DefaultTableModel table;
    int num = 0;
    /**
     * Creates new form Vehiculos13
     */
    public Vehiculos13() {
        initComponents();
         this.setLocationRelativeTo(null);
        readBinario();
        Definir();
        Datos();
              
            }
    
    
    public void Definir(){
   String datos [][]= {};
    String columna[]= {"Nombre", "Punteria","Ataque", "Defensa", "Tipo", "Precio"};
    
    
        
  
    
    table= new DefaultTableModel(datos, columna);
  jTable1Vehi.setModel(table);
    
}
    public void readBinario(){
        capsulavehiculo.clear();
        ObjectInputStream binario = null;
        try {
             
            File file_av = new File(pathVehiculos);
            
            if (file_av.isDirectory()) {
                
                for (String string2:file_av.list()) {

                    binario = new ObjectInputStream(new FileInputStream(pathVehiculos+string2));
                    Vehiculos av = (Vehiculos) binario.readObject();
                    capsulavehiculo.add(av);

                }
                
            }else JOptionPane.showMessageDialog(null, "No hay Vehiculos", "informacion", JOptionPane.WARNING_MESSAGE);
                 
        } catch (Exception ext) {
            ext.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (binario != null ) {
                    
                    binario.close();
                }
            } catch (IOException ext) {
                Logger.getLogger(CrearVehiculos12.class.getName()).log(Level.SEVERE, null, ext);
            }
        }
        
    }
    
            public void Datos(){
                Vehiculos c;
                for (int i = 0; i < CrearVehiculos12.capsulavehiculo.size(); i++) {
                    c= (Vehiculos)CrearVehiculos12.capsulavehiculo.get(i);
                    table.insertRow(num, new Object []{ });
                    table.setValueAt(c.getNombreV(), num, 0);
                    table.setValueAt(c.getPunteriaV(), num, 1);
                    table.setValueAt(c.getAtaqueV(), num, 2);
                    table.setValueAt(c.getDefensaV(), num, 3);
                    table.setValueAt(c.getTipo(), num, 4);
                    table.setValueAt(c.getPrecioV(),num,5);
                    
                 
                }
                    
                
                
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Vehi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1Vehi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1Vehi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 220));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 255));
        jButton1.setText("REGRESAR");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 160, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 255, 255));
        jButton2.setText("SELECCIONAR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vehiculos.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(810, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(810, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(810, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 741, 376));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Vehi;
    // End of variables declaration//GEN-END:variables
}
